version: '3.7'

services:
  wiki_generator:
    build:
      dockerfile: Dockerfile
    container_name: wiki_generator
    restart: always
    expose:
      - 8006
    networks:
      - server
    volumes:
      - /wiki_generator
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/Wiki_Data"

  nginx:
    build:
      dockerfile: nginx/Dockerfile
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - wiki_generator

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    networks:
      - server
    ports:
      - "27017:27017"

networks:
  server:
    name: server
    driver: overlay
    attachable: true
